pipeline {
  
    agent any

    stages {
        stage("Build Jar") {
            steps {
                bat "mvn -f flight/pom.xml clean package -DskipTests"
            }
        }

        stage("Build Image") {
            steps {
                bat "docker build -t jkhan1991/selenium ./flight/"
            }
        }

        stage("Push Image") {

            environment {
                DOCKER_HUB = credentials('Docker_Info')
            }
                    steps {
                        bat 'docker login -u ${DOCKER_HUB_USR} -p ${DOCKER_HUB_PSW}'
                        bat "docker push jkhan1991/selenium ./flight/"
                    }
                }
    }
}
